namespace IDS.Data.Models
{
    /// <summary>
    /// Represents a security alert generated by the IDS system
    /// </summary>
    public class SecurityAlert
    {
        public int Id { get; set; }
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
        public string Severity { get; set; } = "Medium"; // Critical, High, Medium, Low, Info
        public string AlertType { get; set; } = string.Empty; // Intrusion, Malware, DDoS, Brute Force, etc.
        public string SourceIP { get; set; } = string.Empty;
        public string DestinationIP { get; set; } = string.Empty;
        public int? SourcePort { get; set; }
        public int? DestinationPort { get; set; }
        public string Protocol { get; set; } = string.Empty; // TCP, UDP, ICMP, etc.
        public string Message { get; set; } = string.Empty;
   public string? RawPacketData { get; set; }
        public bool IsAcknowledged { get; set; } = false;
     public string? AcknowledgedByUserId { get; set; }
  public DateTime? AcknowledgedAt { get; set; }
        public string? Notes { get; set; }
    }

    /// <summary>
    /// Represents a network traffic event captured by the NIDS
  /// </summary>
    public class NetworkEvent
    {
        public long Id { get; set; }
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
        public string SourceIP { get; set; } = string.Empty;
        public string DestinationIP { get; set; } = string.Empty;
        public int SourcePort { get; set; }
        public int DestinationPort { get; set; }
        public string Protocol { get; set; } = string.Empty;
    public long PacketSize { get; set; }
        public string Classification { get; set; } = "Normal"; // Normal, Attack, Suspicious
        public string? AttackType { get; set; } // If classified as attack: DoS, Probe, R2L, U2R, etc.
        public double? ConfidenceScore { get; set; } // ML model confidence
    }

    /// <summary>
  /// System configuration settings stored in database
 /// </summary>
    public class SystemSetting
    {
        public int Id { get; set; }
  public string Key { get; set; } = string.Empty;
   public string Value { get; set; } = string.Empty;
        public string? Description { get; set; }
        public DateTime LastModified { get; set; } = DateTime.UtcNow;
        public string? ModifiedByUserId { get; set; }
    }

    /// <summary>
    /// Audit log for tracking admin actions
    /// </summary>
    public class AuditLog
    {
    public long Id { get; set; }
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
        public string UserId { get; set; } = string.Empty;
   public string UserEmail { get; set; } = string.Empty;
        public string Action { get; set; } = string.Empty; // Login, Logout, CreateUser, DeleteUser, ViewData, etc.
 public string EntityType { get; set; } = string.Empty; // User, Alert, NetworkEvent, etc.
        public string? EntityId { get; set; }
  public string? Details { get; set; }
        public string? IpAddress { get; set; }
  }

    /// <summary>
    /// Dashboard metrics snapshot for quick loading
    /// </summary>
    public class DashboardMetrics
    {
        public int Id { get; set; }
    public DateTime SnapshotTime { get; set; } = DateTime.UtcNow;
        public int TotalAlerts { get; set; }
        public int CriticalAlerts { get; set; }
   public int HighAlerts { get; set; }
  public int MediumAlerts { get; set; }
        public int LowAlerts { get; set; }
     public long TotalNetworkEvents { get; set; }
        public long NormalTraffic { get; set; }
 public long SuspiciousTraffic { get; set; }
public long AttackTraffic { get; set; }
      public int ActiveUsers { get; set; }
    }
}
