// <auto-generated />
using System;
using IDS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IDS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923143405_AddSecurityChangeRequests")]
    partial class AddSecurityChangeRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IDS.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("General");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.AttackTraffic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AckFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("AckFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ActiveCov")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMax")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMean")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMedian")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMin")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMode")
                        .HasColumnType("float");

                    b.Property<double>("ActiveSkewness")
                        .HasColumnType("float");

                    b.Property<double>("ActiveStd")
                        .HasColumnType("float");

                    b.Property<double>("ActiveVariance")
                        .HasColumnType("float");

                    b.Property<string>("AttackCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("AvgBwdBulkRate")
                        .HasColumnType("float");

                    b.Property<double>("AvgSegmentSize")
                        .HasColumnType("float");

                    b.Property<int>("BwdAckFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("BwdAckFlagPercentageInBwdPackets")
                        .HasColumnType("float");

                    b.Property<double>("BwdAckFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("BwdBulkDuration")
                        .HasColumnType("float");

                    b.Property<int>("BwdBulkStateCount")
                        .HasColumnType("int");

                    b.Property<double>("BwdBytesRate")
                        .HasColumnType("float");

                    b.Property<int>("BwdFinFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("BwdInitWinBytes")
                        .HasColumnType("int");

                    b.Property<double>("BwdMeanHeaderBytes")
                        .HasColumnType("float");

                    b.Property<int>("BwdPacketsCount")
                        .HasColumnType("int");

                    b.Property<double>("BwdPacketsIatMax")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMean")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMedian")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMin")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMode")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatStd")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatTotal")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatVariance")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsRate")
                        .HasColumnType("float");

                    b.Property<double>("BwdPayloadBytesMax")
                        .HasColumnType("float");

                    b.Property<double>("BwdPayloadBytesMedian")
                        .HasColumnType("float");

                    b.Property<double>("BwdPayloadBytesStd")
                        .HasColumnType("float");

                    b.Property<int>("BwdRstFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("BwdSynFlagCounts")
                        .HasColumnType("int");

                    b.Property<long>("BwdTotalHeaderBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("BwdTotalPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("BwdUrgFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("BytesRate")
                        .HasColumnType("float");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<double>("CovBwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("CovFwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("CovHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<int>("CwrFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("DeltaStart")
                        .HasColumnType("float");

                    b.Property<double>("DownUpRate")
                        .HasColumnType("float");

                    b.Property<int>("DstPort")
                        .HasColumnType("int");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<int>("EceFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FinFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdAckFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("FwdAckFlagPercentageInFwdPackets")
                        .HasColumnType("float");

                    b.Property<double>("FwdAckFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("FwdAvgSegmentSize")
                        .HasColumnType("float");

                    b.Property<double>("FwdBytesRate")
                        .HasColumnType("float");

                    b.Property<int>("FwdFinFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdInitWinBytes")
                        .HasColumnType("int");

                    b.Property<double>("FwdMeanHeaderBytes")
                        .HasColumnType("float");

                    b.Property<int>("FwdPacketsCount")
                        .HasColumnType("int");

                    b.Property<double>("FwdPacketsIatCov")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMax")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMean")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMedian")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMin")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMode")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatSkewness")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatStd")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatTotal")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatVariance")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsRate")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesCov")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesMax")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesMedian")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesSkewness")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesStd")
                        .HasColumnType("float");

                    b.Property<int>("FwdPshFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdRstFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdSynFlagCounts")
                        .HasColumnType("int");

                    b.Property<long>("FwdTotalHeaderBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("FwdTotalPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("FwdUrgFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("HandshakeDuration")
                        .HasColumnType("float");

                    b.Property<string>("HandshakeState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("IdleCov")
                        .HasColumnType("float");

                    b.Property<double>("IdleMax")
                        .HasColumnType("float");

                    b.Property<double>("IdleMean")
                        .HasColumnType("float");

                    b.Property<double>("IdleMedian")
                        .HasColumnType("float");

                    b.Property<double>("IdleMin")
                        .HasColumnType("float");

                    b.Property<double>("IdleMode")
                        .HasColumnType("float");

                    b.Property<double>("IdleSkewness")
                        .HasColumnType("float");

                    b.Property<double>("IdleStd")
                        .HasColumnType("float");

                    b.Property<double>("IdleVariance")
                        .HasColumnType("float");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("MaxBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MaxBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MaxFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MaxHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MaxPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanBwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MeanFwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MeanHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("MeanHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MeanPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MedianBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MedianFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MedianFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MedianPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MinFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MinPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModeBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModeFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModeFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("ModeFwdPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModePacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModePacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("ModePayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double>("PacketIatMax")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatMin")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatStd")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatTotal")
                        .HasColumnType("float");

                    b.Property<int>("PacketsCount")
                        .HasColumnType("int");

                    b.Property<double>("PacketsIatCov")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatMean")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatMedian")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatMode")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatVariance")
                        .HasColumnType("float");

                    b.Property<double>("PacketsRate")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesCov")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesMax")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesMean")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesMedian")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesSkewness")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesStd")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesVariance")
                        .HasColumnType("float");

                    b.Property<int>("PshFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("RstFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("RstFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("SkewnessBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<string>("SrcIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<double>("StdFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("StdHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("StdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<long>("SubflowBwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowBwdPackets")
                        .HasColumnType("int");

                    b.Property<long>("SubflowFwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowFwdPackets")
                        .HasColumnType("int");

                    b.Property<int>("SynFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("SynFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalHeaderBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("UrgFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("VarianceHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("VariancePacketsDeltaTime")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AttackType");

                    b.HasIndex("DstPort");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("Label");

                    b.HasIndex("Severity");

                    b.HasIndex("SrcIp");

                    b.HasIndex("Timestamp");

                    b.ToTable("Attack_Table", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.BenignTraffic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AckFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("AckFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("ActiveCov")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMax")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMean")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMedian")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMin")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMode")
                        .HasColumnType("float");

                    b.Property<double>("ActiveSkewness")
                        .HasColumnType("float");

                    b.Property<double>("ActiveStd")
                        .HasColumnType("float");

                    b.Property<double>("ActiveVariance")
                        .HasColumnType("float");

                    b.Property<double>("AvgBwdBulkRate")
                        .HasColumnType("float");

                    b.Property<double>("AvgSegmentSize")
                        .HasColumnType("float");

                    b.Property<int>("BwdAckFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("BwdAckFlagPercentageInBwdPackets")
                        .HasColumnType("float");

                    b.Property<double>("BwdAckFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("BwdBulkDuration")
                        .HasColumnType("float");

                    b.Property<int>("BwdBulkStateCount")
                        .HasColumnType("int");

                    b.Property<double>("BwdBytesRate")
                        .HasColumnType("float");

                    b.Property<int>("BwdFinFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("BwdInitWinBytes")
                        .HasColumnType("int");

                    b.Property<double>("BwdMeanHeaderBytes")
                        .HasColumnType("float");

                    b.Property<int>("BwdPacketsCount")
                        .HasColumnType("int");

                    b.Property<double>("BwdPacketsIatMax")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMean")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMedian")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMin")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMode")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatStd")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatTotal")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatVariance")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsRate")
                        .HasColumnType("float");

                    b.Property<double>("BwdPayloadBytesMax")
                        .HasColumnType("float");

                    b.Property<double>("BwdPayloadBytesMedian")
                        .HasColumnType("float");

                    b.Property<double>("BwdPayloadBytesStd")
                        .HasColumnType("float");

                    b.Property<int>("BwdRstFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("BwdSynFlagCounts")
                        .HasColumnType("int");

                    b.Property<long>("BwdTotalHeaderBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("BwdTotalPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("BwdUrgFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("BytesRate")
                        .HasColumnType("float");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<double>("CovBwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("CovFwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("CovHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<int>("CwrFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("DeltaStart")
                        .HasColumnType("float");

                    b.Property<double>("DownUpRate")
                        .HasColumnType("float");

                    b.Property<int>("DstPort")
                        .HasColumnType("int");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<int>("EceFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FinFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdAckFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("FwdAckFlagPercentageInFwdPackets")
                        .HasColumnType("float");

                    b.Property<double>("FwdAckFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("FwdAvgSegmentSize")
                        .HasColumnType("float");

                    b.Property<double>("FwdBytesRate")
                        .HasColumnType("float");

                    b.Property<int>("FwdFinFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdInitWinBytes")
                        .HasColumnType("int");

                    b.Property<double>("FwdMeanHeaderBytes")
                        .HasColumnType("float");

                    b.Property<int>("FwdPacketsCount")
                        .HasColumnType("int");

                    b.Property<double>("FwdPacketsIatCov")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMax")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMean")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMedian")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMin")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMode")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatSkewness")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatStd")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatTotal")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatVariance")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsRate")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesCov")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesMax")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesMedian")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesSkewness")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesStd")
                        .HasColumnType("float");

                    b.Property<int>("FwdPshFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdRstFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdSynFlagCounts")
                        .HasColumnType("int");

                    b.Property<long>("FwdTotalHeaderBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("FwdTotalPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("FwdUrgFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("HandshakeDuration")
                        .HasColumnType("float");

                    b.Property<string>("HandshakeState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("IdleCov")
                        .HasColumnType("float");

                    b.Property<double>("IdleMax")
                        .HasColumnType("float");

                    b.Property<double>("IdleMean")
                        .HasColumnType("float");

                    b.Property<double>("IdleMedian")
                        .HasColumnType("float");

                    b.Property<double>("IdleMin")
                        .HasColumnType("float");

                    b.Property<double>("IdleMode")
                        .HasColumnType("float");

                    b.Property<double>("IdleSkewness")
                        .HasColumnType("float");

                    b.Property<double>("IdleStd")
                        .HasColumnType("float");

                    b.Property<double>("IdleVariance")
                        .HasColumnType("float");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("MaxBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MaxBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MaxFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MaxHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MaxPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanBwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MeanFwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MeanHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("MeanHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MeanPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MedianBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MedianFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MedianFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MedianPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MinFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MinPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModeBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModeFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModeFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("ModeFwdPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModePacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModePacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("ModePayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PacketIatMax")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatMin")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatStd")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatTotal")
                        .HasColumnType("float");

                    b.Property<int>("PacketsCount")
                        .HasColumnType("int");

                    b.Property<double>("PacketsIatCov")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatMean")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatMedian")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatMode")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatVariance")
                        .HasColumnType("float");

                    b.Property<double>("PacketsRate")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesCov")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesMax")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesMean")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesMedian")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesSkewness")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesStd")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesVariance")
                        .HasColumnType("float");

                    b.Property<int>("PshFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("RstFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("RstFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<string>("SrcIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<double>("StdFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("StdHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("StdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<long>("SubflowBwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowBwdPackets")
                        .HasColumnType("int");

                    b.Property<long>("SubflowFwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowFwdPackets")
                        .HasColumnType("int");

                    b.Property<int>("SynFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("SynFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalHeaderBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("UrgFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("VarianceHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("VariancePacketsDeltaTime")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DstPort");

                    b.HasIndex("Label");

                    b.HasIndex("SrcIp");

                    b.HasIndex("Timestamp");

                    b.ToTable("Benign_Table", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientMessageId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientCiphertext")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipientKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecipientNonce")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("SenderCiphertext")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SenderNonce")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId", "Id");

                    b.HasIndex("SenderId", "ClientMessageId")
                        .IsUnique();

                    b.HasIndex("SenderId", "RecipientId", "Id");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.ChatPublicKey", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SubjectPublicKeyInfo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("UserId");

                    b.ToTable("ChatPublicKeys", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.DashboardMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("int");

                    b.Property<long>("AttackTraffic")
                        .HasColumnType("bigint");

                    b.Property<int>("CriticalAlerts")
                        .HasColumnType("int");

                    b.Property<int>("HighAlerts")
                        .HasColumnType("int");

                    b.Property<int>("LowAlerts")
                        .HasColumnType("int");

                    b.Property<int>("MediumAlerts")
                        .HasColumnType("int");

                    b.Property<long>("NormalTraffic")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("SuspiciousTraffic")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalAlerts")
                        .HasColumnType("int");

                    b.Property<long>("TotalNetworkEvents")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotTime");

                    b.ToTable("DashboardMetrics", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.LogFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("LogFiles", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.NetworkEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttackType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("DestinationIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("int");

                    b.Property<long>("PacketSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("SourcePort")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Classification");

                    b.HasIndex("Timestamp");

                    b.ToTable("NetworkEvents", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.RawPacket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AckFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("AckFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("ActiveCov")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMax")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMean")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMedian")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMin")
                        .HasColumnType("float");

                    b.Property<double>("ActiveMode")
                        .HasColumnType("float");

                    b.Property<double>("ActiveSkewness")
                        .HasColumnType("float");

                    b.Property<double>("ActiveStd")
                        .HasColumnType("float");

                    b.Property<double>("ActiveVariance")
                        .HasColumnType("float");

                    b.Property<double>("AvgBwdBulkRate")
                        .HasColumnType("float");

                    b.Property<double>("AvgSegmentSize")
                        .HasColumnType("float");

                    b.Property<int>("BwdAckFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("BwdAckFlagPercentageInBwdPackets")
                        .HasColumnType("float");

                    b.Property<double>("BwdAckFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("BwdBulkDuration")
                        .HasColumnType("float");

                    b.Property<int>("BwdBulkStateCount")
                        .HasColumnType("int");

                    b.Property<double>("BwdBytesRate")
                        .HasColumnType("float");

                    b.Property<int>("BwdFinFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("BwdInitWinBytes")
                        .HasColumnType("int");

                    b.Property<double>("BwdMeanHeaderBytes")
                        .HasColumnType("float");

                    b.Property<int>("BwdPacketsCount")
                        .HasColumnType("int");

                    b.Property<double>("BwdPacketsIatMax")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMean")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMedian")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMin")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatMode")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatStd")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatTotal")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsIatVariance")
                        .HasColumnType("float");

                    b.Property<double>("BwdPacketsRate")
                        .HasColumnType("float");

                    b.Property<double>("BwdPayloadBytesMax")
                        .HasColumnType("float");

                    b.Property<double>("BwdPayloadBytesMedian")
                        .HasColumnType("float");

                    b.Property<double>("BwdPayloadBytesStd")
                        .HasColumnType("float");

                    b.Property<int>("BwdRstFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("BwdSynFlagCounts")
                        .HasColumnType("int");

                    b.Property<long>("BwdTotalHeaderBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("BwdTotalPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("BwdUrgFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("BytesRate")
                        .HasColumnType("float");

                    b.Property<string>("Classification")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("ClassifiedRecordId")
                        .HasColumnType("bigint");

                    b.Property<double>("CovBwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("CovFwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("CovHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("CovPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<int>("CwrFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("DeltaStart")
                        .HasColumnType("float");

                    b.Property<double>("DownUpRate")
                        .HasColumnType("float");

                    b.Property<int>("DstPort")
                        .HasColumnType("int");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<int>("EceFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FinFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdAckFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("FwdAckFlagPercentageInFwdPackets")
                        .HasColumnType("float");

                    b.Property<double>("FwdAckFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("FwdAvgSegmentSize")
                        .HasColumnType("float");

                    b.Property<double>("FwdBytesRate")
                        .HasColumnType("float");

                    b.Property<int>("FwdFinFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdInitWinBytes")
                        .HasColumnType("int");

                    b.Property<double>("FwdMeanHeaderBytes")
                        .HasColumnType("float");

                    b.Property<int>("FwdPacketsCount")
                        .HasColumnType("int");

                    b.Property<double>("FwdPacketsIatCov")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMax")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMean")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMedian")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMin")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatMode")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatSkewness")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatStd")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatTotal")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsIatVariance")
                        .HasColumnType("float");

                    b.Property<double>("FwdPacketsRate")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesCov")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesMax")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesMedian")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesSkewness")
                        .HasColumnType("float");

                    b.Property<double>("FwdPayloadBytesStd")
                        .HasColumnType("float");

                    b.Property<int>("FwdPshFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdRstFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("FwdSynFlagCounts")
                        .HasColumnType("int");

                    b.Property<long>("FwdTotalHeaderBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("FwdTotalPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("FwdUrgFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("HandshakeDuration")
                        .HasColumnType("float");

                    b.Property<string>("HandshakeState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("IdleCov")
                        .HasColumnType("float");

                    b.Property<double>("IdleMax")
                        .HasColumnType("float");

                    b.Property<double>("IdleMean")
                        .HasColumnType("float");

                    b.Property<double>("IdleMedian")
                        .HasColumnType("float");

                    b.Property<double>("IdleMin")
                        .HasColumnType("float");

                    b.Property<double>("IdleMode")
                        .HasColumnType("float");

                    b.Property<double>("IdleSkewness")
                        .HasColumnType("float");

                    b.Property<double>("IdleStd")
                        .HasColumnType("float");

                    b.Property<double>("IdleVariance")
                        .HasColumnType("float");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("MaxBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MaxBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MaxFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MaxHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MaxPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanBwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MeanFwdHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MeanHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("MeanHeaderBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MeanPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MeanPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MedianBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MedianFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MedianFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MedianPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("MinFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("MinPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModeBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModeFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModeFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("ModeFwdPayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModePacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("ModePacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("ModePayloadBytesDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatMax")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatMin")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatStd")
                        .HasColumnType("float");

                    b.Property<double>("PacketIatTotal")
                        .HasColumnType("float");

                    b.Property<int>("PacketsCount")
                        .HasColumnType("int");

                    b.Property<double>("PacketsIatCov")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatMean")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatMedian")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatMode")
                        .HasColumnType("float");

                    b.Property<double>("PacketsIatVariance")
                        .HasColumnType("float");

                    b.Property<double>("PacketsRate")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesCov")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesMax")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesMean")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesMedian")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesSkewness")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesStd")
                        .HasColumnType("float");

                    b.Property<double>("PayloadBytesVariance")
                        .HasColumnType("float");

                    b.Property<int>("PshFlagCounts")
                        .HasColumnType("int");

                    b.Property<int>("RstFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("RstFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessBwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessBwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessFwdPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessPacketsDeltaLen")
                        .HasColumnType("float");

                    b.Property<double>("SkewnessPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<string>("SrcIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<double>("StdFwdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<double>("StdHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("StdPacketsDeltaTime")
                        .HasColumnType("float");

                    b.Property<long>("SubflowBwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowBwdPackets")
                        .HasColumnType("int");

                    b.Property<long>("SubflowFwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowFwdPackets")
                        .HasColumnType("int");

                    b.Property<int>("SynFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("SynFlagPercentageInTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalHeaderBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalPayloadBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("UrgFlagCounts")
                        .HasColumnType("int");

                    b.Property<double>("VarianceHeaderBytes")
                        .HasColumnType("float");

                    b.Property<double>("VariancePacketsDeltaTime")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DstPort");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("Label");

                    b.HasIndex("SrcIp");

                    b.HasIndex("Timestamp");

                    b.ToTable("RawPackets", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.SecurityAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DestinationIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("DestinationPort")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RawPacketData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("SourcePort")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("Severity");

                    b.HasIndex("Timestamp");

                    b.ToTable("SecurityAlerts", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.SecurityChangeRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestedByEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequesterSecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TargetSecurityStamp")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TargetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SecurityChangeRequests");
                });

            modelBuilder.Entity("IDS.Data.Models.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SourceAttackId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubmittedByEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubmittedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Priority");

                    b.HasIndex("SourceAttackId")
                        .IsUnique()
                        .HasFilter("[SourceAttackId] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("SupportTickets", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.TicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFromSupport")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComments", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IDS.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("IDS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IDS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IDS.Data.Models.ChatPublicKey", b =>
                {
                    b.HasOne("IDS.Data.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("IDS.Data.Models.ChatPublicKey", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IDS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IDS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IDS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
